publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "http://example.org/"
canonifyurls = true
theme = "hugo-academic-group"
title = "Academic group name"
math = true
copyright = "&copy; Your Name, 2016 "

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "Your name"
  email = "mail@example.org"
  address = "3566 Spirit Drive NEW HAVEN Connecticut"

  slogan = "Brain-Inspired Vision Lab"
  slogan_text = "USTC 中国科学技术大学"

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 3
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 10
    title = "News"
    subtitle = ""
    str_all = "More News"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Publications"
      url = "/#publications"
      weight = 2

  [[menu.main]]
      name = "Members"
      url = "/#members"
      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 7
